config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :event_tasks
  resources :events

  root 'home#home'

  get 'contact', to: 'home#contact'
  post 'request_contact', to:'home#request_contact'

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  extend SimpleCalendar

  validates :title, :date, presence: true
  has_many :event_tasks, dependent: :destroy
  belongs_to :user

  scope :user_events, ->(user){ where(['user_id = ?', user.id])}

  def start_time
    self.event.date
  end

end

app/models/event_task.rb
class EventTask < ApplicationRecord
  
  belongs_to :event
  validates :title, :event, presence: true

  scope :user_event_tasks, ->(user) {joins(:event).where(['user_id=?', user.id])}
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :date, presence: true
  belongs_to :user

  scope :user_tasks, ->(user){ where(['user_id = ?', user.id])}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_tasks_controller.rb
class EventTasksController < ApplicationController
  before_action :set_event, only: [:new, :create]
  before_action :set_event_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /event_tasks
  # GET /event_tasks.json
  def index
    @event_tasks = EventTask.user_event_tasks(current_user)
  end

  # GET /event_tasks/1
  # GET /event_tasks/1.json
  def show
  end

  # GET /event_tasks/new
  def new
    @event_task = @event.event_tasks.new
  end

  # GET /event_tasks/1/edit
  def edit
  end

  # POST /event_tasks
  # POST /event_tasks.json
  def create
    @event_task = @event.event_tasks.new(event_task_params)

    respond_to do |format|
      if @event_task.save
        format.html { redirect_to @event_task, notice: 'Event task was successfully created.' }
        format.json { render :show, status: :created, location: @event_task }
      else
        format.html { render :new }
        format.json { render json: @event_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_tasks/1
  # PATCH/PUT /event_tasks/1.json
  def update
    respond_to do |format|
      if @event_task.update(event_task_params)
        format.html { redirect_to @event_task, notice: 'Event task was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_task }
      else
        format.html { render :edit }
        format.json { render json: @event_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_tasks/1
  # DELETE /event_tasks/1.json
  def destroy
    @event_task.destroy
    respond_to do |format|
      format.html { redirect_to event_tasks_url, notice: 'Event task was successfully destroyed.' }
      format.js {flash[:notice] = 'Task was successfully destroyed'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_task
      @event_task = EventTask.find(params[:id])
    end

    def set_event
      @event = Event.find_by(id: params[:event_id]) || Event.find(event_task_params[:event_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_task_params
      params.require(:event_task).permit(:event_id, :title, :completed)
    end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.user_events(current_user)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :start, :end, :location, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def contact
  end


  # POST method to for contact form
  def request_contact

      name = params[:name]
      email = params[:email]
      telephone = params[:telephone]
      message = params[:message]

      # shows error alert if email is blank
      if email.blank?
        flash[:alert] = I18n.t('home.request_contact.no_email')
      else
        ContactMailer.contact_email(email,name,telephone,message).deliver_now
        flash[:notice] = I18n.t('home.request_contact.email_sent')
      end

      #redirect back to home page
        redirect_to root_path
      end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.user_tasks(current_user)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :date, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_tasks_helper.rb
module EventTasksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/event_tasks/_form.html.haml
/ Form partial that can be used in several views /

= form_for @event_task do |f|
  - if @event_task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event_task.errors.count, "error")} prohibited this event_task from being saved:"
      %ul
        - @event_task.errors.full_messages.each do |message|
          %li= message


  .field
    = f.label :event
    = @event_task.event.title
    = f.hidden_field :event_id, value: @event_task.event.id
  .field
    = f.label :title
    = f.text_area :title, :id => "txt"
  .field
    = f.label :completed
    = f.check_box :completed
  .actions
    = f.submit t('save')
  #reset
    %button{name: "button", type: "button"} Clear

app/views/event_tasks/destroy.js.haml
/ removes task from the view once it gets deleted /

$('#event_task_#{@event_task.id}').hide();
console.log("deleted")

app/views/event_tasks/edit.html.haml
%h1=t('.header')

/ Uses the form partial so user is able to edit information /
= render 'form'

= link_to t('open'), @event_task
\|
= link_to t('back'), @event_task.event

app/views/event_tasks/index.html.haml
%h1=t('.header')

%table
  %thead
    %tr
      %th=t('.event')
      %th=t('.title')
      %th=t('.completed')
      %th
      %th
      %th

  %tbody
    - @event_tasks.each do |event_task|
      %tr
        %td= event_task.event.title
        %td= event_task.title
        %td= event_task.completed
        %td= link_to t('open'), event_task
        %td= link_to t('edit'), edit_event_task_path(event_task)
        %td= link_to t('destroy'), event_task, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/event_tasks/new.html.haml
%h1=t('.header')

/ Uses form partial to allow user to input new information /
= render 'form'

/ links user back to the event /
= link_to t('back'), @event_task.event

app/views/event_tasks/show.html.haml
%p
  %b=t('.event')
  = @event_task.event.title
%p
  %b=t('.title')
  = @event_task.title
%p
  %b=t('.completed')
  = @event_task.completed


= link_to t('edit'), edit_event_task_path(@event_task)
\|

/ Links user back to the event instead of the event_task index /
= link_to t('done'), @event_task.event

app/views/events/_form.html.haml
/ Form partial that can be used in several views /

= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .txt
    = f.label :title
    = f.text_field :title, :id => "txt"
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :start
    = f.time_select :start
  .field
    = f.label :end
    = f.time_select :end
  .txt
    = f.label :location
    = f.text_area :location, :id => "txt1"
  .txt
    = f.label :description
    = f.text_area :description, :id => "txt2"
  .actions
    = f.submit t('save')
  #reset
    %button{name: "button", type: "button"} Clear

app/views/events/edit.html.haml
%h1=t('.header')

/ Uses the form partial so user is able to edit information /
= render 'form'

= link_to t('open'), @event
\|
= link_to t('back'), events_path

app/views/events/index.html.haml
%h1=t('.header')

/ Events table does not have description column - use show to view description as description may be too long /

%table
  %thead
    %tr
      %th=t('.title')
      %th=t('.date')
      %th=t('.start')
      %th=t('.end')
      %th=t('.location')
      %th
      %th
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= event.title
        %td= event.date.strftime('%a, %d %b %Y')
        %td= event.start.strftime('%H:%M')
        %td= event.end.strftime('%H:%M')
        %td= event.location
        %td= link_to t('open'), event
        %td= link_to t('edit'), edit_event_path(event)
        %td= link_to t('destroy'), event, method: :delete, data: { confirm: 'Are you sure?' }

%br

.button
  = link_to t('.event'), new_event_path, :class => "button btn btn-default"

app/views/events/new.html.haml
%h1=t('.header')

/ Uses form partial to allow user to input new information /
= render 'form'

= link_to t('back'), events_path

app/views/events/show.html.haml
#showevent
  %p
    %b=t('.title')
    = @event.title
  %p
    %b=t('.date')
    = @event.date
  %p
    %b=t('.start')
    = @event.start.strftime('%H:%M')
  %p
    %b=t('.end')
    = @event.end.strftime('%H:%M')
  %p
    %b=t('.location')
    = @event.location
  %p
    %b=t('.description')
    = @event.description


  / Table for event's tasks /
  %h3=t('.task')
  %table
    %tbody
      -@event.event_tasks.each do |event_task|
        %tr{id:"event_task_#{event_task.id}"}
        %td= event_task.title
        %td= link_to t('edit'), edit_event_task_path(event_task)
        %td= link_to t('destroy'), event_task, :method=>:delete, :data=>{:confirm=>'Are you sure?'}, :remote => true



  =link_to t('.task'), new_event_task_path(event_id: @event), :class => "button btn btn-default"

  %p

  = link_to t('edit'), edit_event_path(@event)
  \|
  = link_to t('back'), events_path

app/views/home/contact.html.haml
%h1=t('.title')
#contact_p
  %p=t('.contact_us')


/ Form for the contact us page /
#contact
  =form_tag request_contact_path, method: 'post' do
    = label_tag :name, t('.name')
    = text_field_tag :name, '',title: t('.enter_name'), size: 50

    = label_tag :email, t('.email')
    = email_field_tag :email, '', title:t('.enter_email')

    = label_tag :telephone, t('.telephone')
    = telephone_field_tag :telephone, '', title:t('.enter_telephone')

    = label_tag :message, t('.message')
    = text_field_tag :message, '', title:t('.enter_message'), size:100

    =submit_tag t('.submit')

app/views/home/home.html.haml
#title
  %h1=t('.title')
.welcome
  %p=t('.welcome')


/ Shows calendar if user is signed in /
-if user_signed_in?
  = month_calendar datevents: @events do |date, datevents|
    = date.strftime('%d')
    / Shows user's events on calendar with link to event /
    - datevents.each do |datevent|
      %div
        = link_to datevent.name, datevent

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}
    %link{href: "https://fonts.googleapis.com/css?family=Patrick+Hand|Satisfy&display=swap", rel: "stylesheet"}/

    %title= t('app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags



  %body
    #page-container
      #container
        / Use partials so header and footer is shown on every page /
        = render 'shared/header'

        - flash.each do |key, value|
          = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?
        = yield

        = render 'shared/footer'

app/views/shared/_footer.html.haml
%footer
  %p=t('.copyright')

app/views/shared/_header.html.haml
%header
/ Bootstrap navigation bar /
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Home
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "/contact"} Contact Us
      / Events and Tasks only shown on navigation bar once user has signed in /
      %ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          %li
            = link_to t('Events'), events_url
          %li
            = link_to t('To Do List'), tasks_url
          %li
            = link_to t('profile'), edit_user_registration_path
          %li
            = link_to t('logout'), destroy_user_session_path, method: 'delete'
        -else
          %li
            = link_to t('login'), new_user_session_path
          %li
            = link_to t('sign_up'), new_user_registration_path

app/views/tasks/_form.html.haml
/ Form partial that can be used in several views /


= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message

  .txt
    = f.label :title
    = f.text_field :title, :id => "txt"
  .txt
    = f.label :description
    = f.text_area :description, :id => "txt2"
  .field
    = f.label :date
    = f.datetime_select :date
  .field
    = f.label :completed
    = f.check_box :completed
  .actions
    = f.submit t('save')
  #reset
    %button{name: "button", type: "button"} Clear

app/views/tasks/edit.html.haml
%h1=t('.header')

/ Uses the form partial so user is able to edit information /
= render 'form'

= link_to t('open'), @task
\|
= link_to t('back'), tasks_path

app/views/tasks/index.html.haml
%h1=t('.header')

/ Task table does not have description column - use show to view description as description may be too long  /


%table
  %thead
    %tr
      %th=t('.title')
      %th=t('.date')
      %th=t('.completed')
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.title
        %td= task.date.strftime('%a, %d %b %Y %H:%M')
        %td= task.completed
        %td= link_to t('open'), task
        %td= link_to t('edit'), edit_task_path(task)
        %td= link_to t('destroy'), task, method: :delete, data: { confirm: 'Are you sure?' }

%br

.button
  = link_to t('.new'), new_task_path, :class => "button btn btn-default"

app/views/tasks/new.html.haml
%h1=t('.header')

/ Uses form partial to allow user to input new information /
= render 'form'

= link_to t('back'), tasks_path

app/views/tasks/show.html.haml
%p
  %b=t('.title')
  = @task.title
%p
  %b=t('.description')
  = @task.description
%p
  %b=t('.date')
  = @task.date.strftime('%a, %d %b %Y %H:%M')
%p
  %b=t('.completed')
  = @task.completed

= link_to t('.edit'), edit_task_path(@task)
\|
= link_to t('.done'), tasks_path